package system

import (
	"bufio"
	"errors"
	"fmt"
	"io/ioutil"
	"os"
	"strings"
	"time"

	"github.com/skmonir/mango-gui/context"
	"github.com/skmonir/mango-gui/utils"
)

func getTemplateHeader(author string, problemName string) string {
	header := "/**\n"
	header += fmt.Sprintf(" *     author:  %v\n", author)
	header += fmt.Sprintf(" *    created:  %v\n", time.Now().Local().Format("2-Jan-2006 15:04:05"))
	header += fmt.Sprintf(" *    problem:  %v\n", problemName)
	header += " *\n"
	header += " *    Template generated by 'mango', https://github.com/skmonir/mango-gui\n"
	header += "**/\n\n"

	return header
}

func getGenericTemplateBody() string {
	body := ""

	body += "#include <bits/stdc++.h>\n"
	body += "\n"
	body += "using namespace std;\n"
	body += "\n"
	body += "const int N = 1e5 + 7;\n"
	body += "const int INF = 1e9 + 7;\n"
	body += "const int MOD = 1e9 + 7;\n"
	body += "\n"
	body += "\n"
	body += "int solver() {\n"
	body += "\t// your code goes here\n"
	body += "\treturn 0;\n"
	body += "}\n"
	body += "\n"
	body += "\n"
	body += "int main() {\n"
	body += "\tios::sync_with_stdio(0), cin.tie(0);\n"
	body += "\tint tt = 1;\n"
	body += "\t// cin >> tt;\n"
	body += "\tfor (int t = 1; t <= tt; ++t) {\n"
	body += "\t\t// cout << \"Case \" << t << \": \";\n"
	body += "\t\tsolver();\n"
	body += "\t}\n"
	body += "\treturn 0;\n"
	body += "}"

	return body
}

func CopyTemplateToSource(config *context.AppConfig, problemId string) error {
	destPath := config.GetSourceFilePathWithExt(problemId)
	problemInfo, _ := config.GetProblemInfo(problemId)

	if !utils.IsFileExist(destPath) {
		return errors.New("source file not found")
	}

	header := getTemplateHeader(config.Author, problemInfo.Name)
	body := ""

	if config.TemplatePath != "" {
		srcPath := config.TemplatePath

		if !utils.IsFileExist(srcPath) {
			body = getGenericTemplateBody()
		} else {
			srcFile, err := os.Open(srcPath)
			if err != nil {
				body = getGenericTemplateBody()
			} else {
				defer srcFile.Close()
				scanner := bufio.NewScanner(srcFile)
				for scanner.Scan() {
					line := scanner.Text()
					line = strings.TrimRight(line, " ")
					body += line + "\n"
				}

				if err = scanner.Err(); err != nil {
					body = getGenericTemplateBody()
				}
			}
		}
	} else {
		body = getGenericTemplateBody()
	}

	template := header + body
	if err := ioutil.WriteFile(destPath, []byte(template), 0644); err != nil {
		return err
	}

	return nil
}

func CopyTemplateToSourceList(config *context.AppConfig, problemIdList []string) error {
	var err error = nil
	for _, problemId := range problemIdList {
		err = CopyTemplateToSource(config, problemId)
		if err != nil {
			fmt.Println(err.Error())
		}
	}
	return err
}

func CreateSource(config *context.AppConfig, parser Parser, problemId string) (string, error) {
	sourcePath := config.GetSourceDirPath()
	sourceName := problemId + ".cpp"
	if err := utils.CreateFile(sourcePath, sourceName); err != nil {
		return sourceName, err
	}
	if err := CopyTemplateToSource(config, problemId); err != nil {
		return sourceName, err
	}
	return sourceName, nil
}

func CreateSourceList(ctx *context.AppCtx, parser Parser, problemIdList []string) {
	for index, problemId := range problemIdList {
		srcName, err := CreateSource(ctx.Config, parser, problemId)
		status := "[CREATED] Successfully created source " + srcName
		if err != nil {
			status = "[FAILED] Error occured while creating source " + srcName
		} else {
			status += ". Click to open the source file."
		}

		// *ctx.ParserUi.ParsedProblemStatus = append([]string{status}, (*ctx.ParserUi.ParsedProblemStatus)...)
		*ctx.ParserUi.ParsedProblemStatus = append(*ctx.ParserUi.ParsedProblemStatus, status)
		ctx.ParserUi.ParsedProblemListContainer.Refresh()
		ctx.ProgressBar.SetValue(float64(index + 1))
	}
}

func Source(ctx *context.AppCtx) error {
	var parser Parser

	if ctx.ParserUi.OnlineJudgeOptionSelect.Selected == "CodeForces" {
		parser = CodeforcesParser{}
	}

	contestId, problemId, err := parser.ParseContestAndProblemId(ctx.ParserUi.ContestIdInputField.Text)
	if err != nil {
		return err
	}

	if contestId == "" {
		return errors.New("please enter valid contest & problem id combination like 1512G")
	}

	ctx.ParserUi.CurrentContestId = contestId
	ctx.Config.CurrentContestId = contestId
	ctx.Config.OJ = ctx.ParserUi.OnlineJudgeOptionSelect.Selected
	if err := ctx.Config.SaveConfig(); err != nil {
		return err
	}
	ctx.HeaderUi.CurrentContestField.SetText(contestId)
	ctx.HeaderUi.CurrentOnlineJudge.SetText(ctx.ParserUi.OnlineJudgeOptionSelect.Selected)

	*ctx.ParserUi.ParsedProblemStatus = []string{}

	if problemId == "" {
		URL := parser.GetContestUrl(ctx.Config.CurrentContestId)
		body, err := GetHtmlBody(URL)
		if err != nil {
			return err
		}
		problemIdList := parser.GetProblemList(body)
		if len(problemIdList) == 0 {
			return errors.New("no problem id found")
		}
		ctx.ProgressBar.Max = float64(len(problemIdList))
		CreateSourceList(ctx, parser, problemIdList)
	} else {
		ctx.ProgressBar.Max = 1

		srcName, err := CreateSource(ctx.Config, parser, problemId)
		status := "[CREATED] Successfully created source " + srcName
		if err != nil {
			status = "[FAILED] Error occured while creating source " + srcName
		} else {
			status += ". Click to open the source file."
		}
		// *ctx.ParserUi.ParsedProblemStatus = append([]string{status}, (*ctx.ParserUi.ParsedProblemStatus)...)
		*ctx.ParserUi.ParsedProblemStatus = append(*ctx.ParserUi.ParsedProblemStatus, status)
		ctx.ParserUi.ParsedProblemListContainer.Refresh()
		ctx.ProgressBar.SetValue(1)
	}

	return nil
}
